# Generated by Django 3.0 on 2021-01-12 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='disc_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DiscountCode'),
        ),
    ]
