# Generated by Django 3.0 on 2021-01-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_disc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='amount',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
