# Generated by Django 3.0 on 2021-01-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210113_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='amount',
            field=models.FloatField(),
        ),
    ]
