# Generated by Django 3.0 on 2021-01-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210113_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default=123456789009975421, max_length=20),
            preserve_default=False,
        ),
    ]
